# Generated by Django 4.0.2 on 2022-04-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeScreen', '0004_tos_author_tos_outofdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='category',
            field=models.CharField(choices=[('PD', 'Privacy/Data'), ('O', 'Ownership')], default='PD', max_length=2),
        ),
        migrations.AddField(
            model_name='edit',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
        migrations.AddField(
            model_name='edit',
            name='tos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeScreen.tos'),
        ),
        migrations.AddField(
            model_name='tos',
            name='communityCount',
            field=models.IntegerField(default=0),
        ),
    ]
