name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r prototype/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
